version: '2'
x-redash-service: &redash-service
  image: redash/redash:7.0.0.b18042
  depends_on:
    - postgres
    - redis
  env_file: redash.env
  restart: always
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
  redis:
    image: redis:5.0-alpine
    restart: always
  postgres:
    image: postgres:9.5-alpine
    env_file: redash.env
    restart: always
    ports:
      - 15432:15432
  nginx:
    image: redash/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always

  # データソースとなるDBコンテナ
  db_server:
    image: postgres:11
    restart: always
    ports:
      - 25432:25432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=practice
      - POSTGRES_PASSWORD=admin
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # 以下に.sqlとか配備すると、コンテナ起動時に実行してくれる（create tableとかしてくれる）
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d