version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: 'testrepo'

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.9
      
    commands:
      - pip install pytest-testinfra==6.8.0
      - wget https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64
      - chmod 755 hadolint-Linux-x86_64

  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - echo Testing the Dockerfile...
      - ./hadolint-Linux-x86_64 Dockerfile -t warning

      - echo Building the Docker image...          
      - docker build -t ecr-codebuild-test .

  post_build:
    on-failure: ABORT
    commands:
      - echo Build completed on `date`
      - echo Testing the Docker image...
      - py.test --junit-xml=./latest_testinfra_report.xml ./test.py

      - echo test completed!

reports:
  testinfra-reports:
    files:
      - '**/*'
    base-directory: reports/
    file-format: JunitXml