version: '3.8'
services:
  tabpy-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9004:9004"
    volumes:
      - ./script/:/app
    command: /bin/bash -c "tabpy --disable-auth-warning & sleep 5 && python3 /app/tabpy_deploy_ml_model_titanic.py && tail -f /dev/null"
